// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Task struct {
	ID             string
	Description    string
	Status         string
	PullRequestUrl *string
	PrNumber       *int64
	DependsOn      string
	CloseReason    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TaskLog struct {
	ID        int64
	TaskID    string
	Lines     string
	CreatedAt time.Time
}
