// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type GithubToken struct {
	ID             string
	EncryptedToken string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Repo struct {
	ID        string
	Owner     string
	Name      string
	FullName  string
	CreatedAt time.Time
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type Task struct {
	ID                     string
	RepoID                 string
	Description            string
	Status                 string
	PullRequestUrl         *string
	PrNumber               *int64
	DependsOn              string
	CloseReason            *string
	Attempt                int64
	MaxAttempts            int64
	RetryReason            *string
	AcceptanceCriteria     *string
	AgentStatus            *string
	RetryContext           *string
	ConsecutiveFailures    int64
	CostUsd                float64
	MaxCostUsd             *float64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	SkipPr                 int64
	BranchName             *string
	Title                  string
	AcceptanceCriteriaList string
	Model                  *string
	StartedAt              *time.Time
	Ready                  int64
	LastHeartbeatAt        *string
}

type TaskLog struct {
	ID        int64
	TaskID    string
	Lines     string
	CreatedAt time.Time
	Attempt   int64
}
