// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskStatus string

const (
	TaskStatusPending TaskStatus = "pending"
	TaskStatusRunning TaskStatus = "running"
	TaskStatusReview  TaskStatus = "review"
	TaskStatusMerged  TaskStatus = "merged"
	TaskStatusClosed  TaskStatus = "closed"
	TaskStatusFailed  TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed:
		return true
	}
	return false
}

func AllTaskStatusValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed,
	}
}

type GithubToken struct {
	ID             string             `json:"id"`
	EncryptedToken string             `json:"encrypted_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Repo struct {
	ID        string             `json:"id"`
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID                     string             `json:"id"`
	RepoID                 string             `json:"repo_id"`
	Description            string             `json:"description"`
	Status                 TaskStatus         `json:"status"`
	PullRequestUrl         *string            `json:"pull_request_url"`
	PrNumber               *int32             `json:"pr_number"`
	DependsOn              []string           `json:"depends_on"`
	CloseReason            *string            `json:"close_reason"`
	Attempt                int32              `json:"attempt"`
	MaxAttempts            int32              `json:"max_attempts"`
	RetryReason            *string            `json:"retry_reason"`
	AgentStatus            *string            `json:"agent_status"`
	RetryContext           *string            `json:"retry_context"`
	ConsecutiveFailures    int32              `json:"consecutive_failures"`
	CostUsd                float64            `json:"cost_usd"`
	MaxCostUsd             *float64           `json:"max_cost_usd"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	SkipPr                 bool               `json:"skip_pr"`
	BranchName             *string            `json:"branch_name"`
	Title                  string             `json:"title"`
	AcceptanceCriteriaList []string           `json:"acceptance_criteria_list"`
	Model                  *string            `json:"model"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
}

type TaskLog struct {
	ID        int64              `json:"id"`
	TaskID    string             `json:"task_id"`
	Lines     []string           `json:"lines"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Attempt   int32              `json:"attempt"`
}
