// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskStatus string

const (
	TaskStatusPending TaskStatus = "pending"
	TaskStatusRunning TaskStatus = "running"
	TaskStatusReview  TaskStatus = "review"
	TaskStatusMerged  TaskStatus = "merged"
	TaskStatusClosed  TaskStatus = "closed"
	TaskStatusFailed  TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed:
		return true
	}
	return false
}

func AllTaskStatusValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed,
	}
}

type Task struct {
	ID             string             `json:"id"`
	Description    string             `json:"description"`
	Status         TaskStatus         `json:"status"`
	Logs           []string           `json:"logs"`
	PullRequestUrl *string            `json:"pull_request_url"`
	PrNumber       *int32             `json:"pr_number"`
	DependsOn      []string           `json:"depends_on"`
	CloseReason    *string            `json:"close_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
