// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AppendTaskLogs(ctx context.Context, arg AppendTaskLogsParams) error
	ClaimTask(ctx context.Context, id string) (int64, error)
	CloseTask(ctx context.Context, arg CloseTaskParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	ListPendingTasks(ctx context.Context) ([]*Task, error)
	ListTasks(ctx context.Context) ([]*Task, error)
	ListTasksInReview(ctx context.Context) ([]*Task, error)
	ReadTask(ctx context.Context, id string) (*Task, error)
	ReadTaskLogs(ctx context.Context, id string) ([][]string, error)
	ReadTaskStatus(ctx context.Context, id string) (TaskStatus, error)
	SetTaskPullRequest(ctx context.Context, arg SetTaskPullRequestParams) error
	TaskExists(ctx context.Context, id string) (bool, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
